apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rshiny
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rshiny
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rshiny
    spec:
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: docker-rshiny
          image: jinseob2kim/docker-rshiny
          imagePullPolicy: Always
          env:
            - name: USER
              value: "js"
            - name: PASSWORD
              value: "js"
          ports:
            - name: rstudio 
              containerPort: 8787
            - name: shiny 
              containerPort: 3838
          volumeMounts:
            - mountPath: /home/js/ShinyApps
              name: shared-data
          