apiVersion: v1
kind: Service
metadata:
  name: rshiny
spec:
  selector:
    app: rshiny
  ports:
    - port: 80
      targetPort: 3838
      name: shiny
    - port: 8787
      targetPort: 8787
      name: rstudio
  type: LoadBalancer
